### ISSUE TITLE
[FEAT/09-09] Home-Grid Layout

### ISSUE THREAD

**Issue by tigowler** [tigowler/7LOVES#1]
## ✨ Feature Issue
- Home에 표시될 Card Component의 HTML과 CSS 작업을 완료한다.
- 기능 구현이 아닌 화면을 먼저 작업한다.
- Logout 버튼과 기능을 완성한다.

## 📌 To-do
- [x] Logout 버튼과 로그인된 사용자 이름 추가하기
- [x] Card Component HTML CSS 완성하기
- [ ] Grid Layout 완성하기
    - [ ] card component 7개 배치
    - [ ] 자리 이동 구현
